// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/mimsy-cms/mimsy/internal/collection (interfaces: Repository)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	collection "github.com/mimsy-cms/mimsy/internal/collection"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// CollectionExists mocks base method.
func (m *MockRepository) CollectionExists(arg0 context.Context, arg1 string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CollectionExists", arg0, arg1)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CollectionExists indicates an expected call of CollectionExists.
func (mr *MockRepositoryMockRecorder) CollectionExists(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CollectionExists", reflect.TypeOf((*MockRepository)(nil).CollectionExists), arg0, arg1)
}

// CreateCollection mocks base method.
func (m *MockRepository) CreateCollection(arg0 context.Context, arg1, arg2 string, arg3 []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateCollection", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateCollection indicates an expected call of CreateCollection.
func (mr *MockRepositoryMockRecorder) CreateCollection(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCollection", reflect.TypeOf((*MockRepository)(nil).CreateCollection), arg0, arg1, arg2, arg3)
}

// DeleteResource mocks base method.
func (m *MockRepository) DeleteResource(arg0 context.Context, arg1 *collection.Resource) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteResource", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteResource indicates an expected call of DeleteResource.
func (mr *MockRepositoryMockRecorder) DeleteResource(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteResource", reflect.TypeOf((*MockRepository)(nil).DeleteResource), arg0, arg1)
}

// FindAll mocks base method.
func (m *MockRepository) FindAll(arg0 context.Context, arg1 *collection.FindAllParams) ([]collection.Collection, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAll", arg0, arg1)
	ret0, _ := ret[0].([]collection.Collection)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAll indicates an expected call of FindAll.
func (mr *MockRepositoryMockRecorder) FindAll(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAll", reflect.TypeOf((*MockRepository)(nil).FindAll), arg0, arg1)
}

// FindAllGlobals mocks base method.
func (m *MockRepository) FindAllGlobals(arg0 context.Context, arg1 *collection.FindAllParams) ([]collection.Collection, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAllGlobals", arg0, arg1)
	ret0, _ := ret[0].([]collection.Collection)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAllGlobals indicates an expected call of FindAllGlobals.
func (mr *MockRepositoryMockRecorder) FindAllGlobals(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAllGlobals", reflect.TypeOf((*MockRepository)(nil).FindAllGlobals), arg0, arg1)
}

// FindBySlug mocks base method.
func (m *MockRepository) FindBySlug(arg0 context.Context, arg1 string) (*collection.Collection, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindBySlug", arg0, arg1)
	ret0, _ := ret[0].(*collection.Collection)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindBySlug indicates an expected call of FindBySlug.
func (mr *MockRepositoryMockRecorder) FindBySlug(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindBySlug", reflect.TypeOf((*MockRepository)(nil).FindBySlug), arg0, arg1)
}

// FindResource mocks base method.
func (m *MockRepository) FindResource(arg0 context.Context, arg1 *collection.Collection, arg2 string) (*collection.Resource, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindResource", arg0, arg1, arg2)
	ret0, _ := ret[0].(*collection.Resource)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindResource indicates an expected call of FindResource.
func (mr *MockRepositoryMockRecorder) FindResource(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindResource", reflect.TypeOf((*MockRepository)(nil).FindResource), arg0, arg1, arg2)
}

// FindResources mocks base method.
func (m *MockRepository) FindResources(arg0 context.Context, arg1 *collection.Collection) ([]collection.Resource, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindResources", arg0, arg1)
	ret0, _ := ret[0].([]collection.Resource)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindResources indicates an expected call of FindResources.
func (mr *MockRepositoryMockRecorder) FindResources(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindResources", reflect.TypeOf((*MockRepository)(nil).FindResources), arg0, arg1)
}

// FindUserEmail mocks base method.
func (m *MockRepository) FindUserEmail(arg0 context.Context, arg1 int64) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindUserEmail", arg0, arg1)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindUserEmail indicates an expected call of FindUserEmail.
func (mr *MockRepositoryMockRecorder) FindUserEmail(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindUserEmail", reflect.TypeOf((*MockRepository)(nil).FindUserEmail), arg0, arg1)
}

// UpdateCollection mocks base method.
func (m *MockRepository) UpdateCollection(arg0 context.Context, arg1, arg2 string, arg3 []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateCollection", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateCollection indicates an expected call of UpdateCollection.
func (mr *MockRepositoryMockRecorder) UpdateCollection(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCollection", reflect.TypeOf((*MockRepository)(nil).UpdateCollection), arg0, arg1, arg2, arg3)
}

// UpdateResourceContent mocks base method.
func (m *MockRepository) UpdateResourceContent(arg0 context.Context, arg1 *collection.Collection, arg2 string, arg3 map[string]interface{}) (*collection.Resource, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateResourceContent", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(*collection.Resource)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateResourceContent indicates an expected call of UpdateResourceContent.
func (mr *MockRepositoryMockRecorder) UpdateResourceContent(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateResourceContent", reflect.TypeOf((*MockRepository)(nil).UpdateResourceContent), arg0, arg1, arg2, arg3)
}
