// Code generated by MockGen. DO NOT EDIT.
// Source: internal/collection/service.go
//
// Generated by this command:
//
//	mockgen -source=internal/collection/service.go -destination=internal/mocks/collection/mock_service.go -package=mocks CollectionService
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	collection "github.com/mimsy-cms/mimsy/internal/collection"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
	isgomock struct{}
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// DeleteResource mocks base method.
func (m *MockService) DeleteResource(ctx context.Context, resource *collection.Resource) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteResource", ctx, resource)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteResource indicates an expected call of DeleteResource.
func (mr *MockServiceMockRecorder) DeleteResource(ctx, resource any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteResource", reflect.TypeOf((*MockService)(nil).DeleteResource), ctx, resource)
}

// FindAll mocks base method.
func (m *MockService) FindAll(ctx context.Context, params *collection.FindAllParams) ([]collection.Collection, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAll", ctx, params)
	ret0, _ := ret[0].([]collection.Collection)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAll indicates an expected call of FindAll.
func (mr *MockServiceMockRecorder) FindAll(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAll", reflect.TypeOf((*MockService)(nil).FindAll), ctx, params)
}

// FindAllGlobals mocks base method.
func (m *MockService) FindAllGlobals(ctx context.Context, params *collection.FindAllParams) ([]collection.Collection, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAllGlobals", ctx, params)
	ret0, _ := ret[0].([]collection.Collection)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAllGlobals indicates an expected call of FindAllGlobals.
func (mr *MockServiceMockRecorder) FindAllGlobals(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAllGlobals", reflect.TypeOf((*MockService)(nil).FindAllGlobals), ctx, params)
}

// FindBySlug mocks base method.
func (m *MockService) FindBySlug(ctx context.Context, slug string) (*collection.Collection, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindBySlug", ctx, slug)
	ret0, _ := ret[0].(*collection.Collection)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindBySlug indicates an expected call of FindBySlug.
func (mr *MockServiceMockRecorder) FindBySlug(ctx, slug any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindBySlug", reflect.TypeOf((*MockService)(nil).FindBySlug), ctx, slug)
}

// FindResource mocks base method.
func (m *MockService) FindResource(ctx context.Context, arg1 *collection.Collection, slug string) (*collection.Resource, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindResource", ctx, arg1, slug)
	ret0, _ := ret[0].(*collection.Resource)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindResource indicates an expected call of FindResource.
func (mr *MockServiceMockRecorder) FindResource(ctx, arg1, slug any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindResource", reflect.TypeOf((*MockService)(nil).FindResource), ctx, arg1, slug)
}

// FindResources mocks base method.
func (m *MockService) FindResources(ctx context.Context, arg1 *collection.Collection) ([]collection.Resource, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindResources", ctx, arg1)
	ret0, _ := ret[0].([]collection.Resource)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindResources indicates an expected call of FindResources.
func (mr *MockServiceMockRecorder) FindResources(ctx, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindResources", reflect.TypeOf((*MockService)(nil).FindResources), ctx, arg1)
}

// FindUserEmail mocks base method.
func (m *MockService) FindUserEmail(ctx context.Context, id int64) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindUserEmail", ctx, id)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindUserEmail indicates an expected call of FindUserEmail.
func (mr *MockServiceMockRecorder) FindUserEmail(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindUserEmail", reflect.TypeOf((*MockService)(nil).FindUserEmail), ctx, id)
}

// UpdateResourceContent mocks base method.
func (m *MockService) UpdateResourceContent(ctx context.Context, arg1 *collection.Collection, resourceSlug string, content map[string]any) (*collection.Resource, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateResourceContent", ctx, arg1, resourceSlug, content)
	ret0, _ := ret[0].(*collection.Resource)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateResourceContent indicates an expected call of UpdateResourceContent.
func (mr *MockServiceMockRecorder) UpdateResourceContent(ctx, arg1, resourceSlug, content any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateResourceContent", reflect.TypeOf((*MockService)(nil).UpdateResourceContent), ctx, arg1, resourceSlug, content)
}
