// Code generated by MockGen. DO NOT EDIT.
// Source: internal/collection/repository.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	collection "github.com/mimsy-cms/mimsy/internal/collection"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// CollectionExists mocks base method.
func (m *MockRepository) CollectionExists(ctx context.Context, slug string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CollectionExists", ctx, slug)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CollectionExists indicates an expected call of CollectionExists.
func (mr *MockRepositoryMockRecorder) CollectionExists(ctx, slug interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CollectionExists", reflect.TypeOf((*MockRepository)(nil).CollectionExists), ctx, slug)
}

// CreateCollection mocks base method.
func (m *MockRepository) CreateCollection(ctx context.Context, slug, name string, fieldsJson []byte, isGlobal bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateCollection", ctx, slug, name, fieldsJson, isGlobal)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateCollection indicates an expected call of CreateCollection.
func (mr *MockRepositoryMockRecorder) CreateCollection(ctx, slug, name, fieldsJson, isGlobal interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCollection", reflect.TypeOf((*MockRepository)(nil).CreateCollection), ctx, slug, name, fieldsJson, isGlobal)
}

// CreateResource mocks base method.
func (m *MockRepository) CreateResource(ctx context.Context, c *collection.Collection, resourceSlug string, createdBy int64, content map[string]any) (*collection.Resource, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateResource", ctx, c, resourceSlug, createdBy, content)
	ret0, _ := ret[0].(*collection.Resource)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateResource indicates an expected call of CreateResource.
func (mr *MockRepositoryMockRecorder) CreateResource(ctx, c, resourceSlug, createdBy, content interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateResource", reflect.TypeOf((*MockRepository)(nil).CreateResource), ctx, c, resourceSlug, createdBy, content)
}

// DeleteCollection mocks base method.
func (m *MockRepository) DeleteCollection(ctx context.Context, slug string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteCollection", ctx, slug)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteCollection indicates an expected call of DeleteCollection.
func (mr *MockRepositoryMockRecorder) DeleteCollection(ctx, slug interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteCollection", reflect.TypeOf((*MockRepository)(nil).DeleteCollection), ctx, slug)
}

// DeleteResource mocks base method.
func (m *MockRepository) DeleteResource(ctx context.Context, resource *collection.Resource) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteResource", ctx, resource)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteResource indicates an expected call of DeleteResource.
func (mr *MockRepositoryMockRecorder) DeleteResource(ctx, resource interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteResource", reflect.TypeOf((*MockRepository)(nil).DeleteResource), ctx, resource)
}

// FindAll mocks base method.
func (m *MockRepository) FindAll(ctx context.Context, params *collection.FindAllParams) ([]collection.Collection, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAll", ctx, params)
	ret0, _ := ret[0].([]collection.Collection)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAll indicates an expected call of FindAll.
func (mr *MockRepositoryMockRecorder) FindAll(ctx, params interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAll", reflect.TypeOf((*MockRepository)(nil).FindAll), ctx, params)
}

// FindAllGlobals mocks base method.
func (m *MockRepository) FindAllGlobals(ctx context.Context, params *collection.FindAllParams) ([]collection.Collection, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAllGlobals", ctx, params)
	ret0, _ := ret[0].([]collection.Collection)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAllGlobals indicates an expected call of FindAllGlobals.
func (mr *MockRepositoryMockRecorder) FindAllGlobals(ctx, params interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAllGlobals", reflect.TypeOf((*MockRepository)(nil).FindAllGlobals), ctx, params)
}

// FindBySlug mocks base method.
func (m *MockRepository) FindBySlug(ctx context.Context, slug string) (*collection.Collection, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindBySlug", ctx, slug)
	ret0, _ := ret[0].(*collection.Collection)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindBySlug indicates an expected call of FindBySlug.
func (mr *MockRepositoryMockRecorder) FindBySlug(ctx, slug interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindBySlug", reflect.TypeOf((*MockRepository)(nil).FindBySlug), ctx, slug)
}

// FindResource mocks base method.
func (m *MockRepository) FindResource(ctx context.Context, c *collection.Collection, slug string) (*collection.Resource, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindResource", ctx, c, slug)
	ret0, _ := ret[0].(*collection.Resource)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindResource indicates an expected call of FindResource.
func (mr *MockRepositoryMockRecorder) FindResource(ctx, c, slug interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindResource", reflect.TypeOf((*MockRepository)(nil).FindResource), ctx, c, slug)
}

// FindResources mocks base method.
func (m *MockRepository) FindResources(ctx context.Context, c *collection.Collection) ([]collection.Resource, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindResources", ctx, c)
	ret0, _ := ret[0].([]collection.Resource)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindResources indicates an expected call of FindResources.
func (mr *MockRepositoryMockRecorder) FindResources(ctx, c interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindResources", reflect.TypeOf((*MockRepository)(nil).FindResources), ctx, c)
}

// UpdateCollection mocks base method.
func (m *MockRepository) UpdateCollection(ctx context.Context, slug, name string, fieldsJson []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateCollection", ctx, slug, name, fieldsJson)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateCollection indicates an expected call of UpdateCollection.
func (mr *MockRepositoryMockRecorder) UpdateCollection(ctx, slug, name, fieldsJson interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCollection", reflect.TypeOf((*MockRepository)(nil).UpdateCollection), ctx, slug, name, fieldsJson)
}

// UpdateResource mocks base method.
func (m *MockRepository) UpdateResource(ctx context.Context, c *collection.Collection, resourceSlug string, updatedBy int64, content map[string]any) (*collection.Resource, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateResource", ctx, c, resourceSlug, updatedBy, content)
	ret0, _ := ret[0].(*collection.Resource)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateResource indicates an expected call of UpdateResource.
func (mr *MockRepositoryMockRecorder) UpdateResource(ctx, c, resourceSlug, updatedBy, content interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateResource", reflect.TypeOf((*MockRepository)(nil).UpdateResource), ctx, c, resourceSlug, updatedBy, content)
}
