apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
patches:
  - patch: |
      - op: replace
        path: /spec/path
        value: ./clusters/sofliar/overrides/landing
    target:
      kind: Kustomization
      name: "landing"
