apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - pull-secrets.yaml
  - ../../base
patches:
  - patch: |
      - op: replace
        path: /spec/path
        value: ./flux/clusters/sofliar/overrides/landing
    target:
      kind: Kustomization
      name: "landing"
  - patch: |
      - op: replace
        path: /spec/path
        value: ./flux/clusters/sofliar/overrides/web
    target:
      kind: Kustomization
      name: "web"
