apiVersion: v1
kind: Secret
metadata:
    namespace: mimsy
    name: regcred
    annotations:
        replicator.v1.mittwald.de/replicate-to-matching: toolkit.fluxcd.io/tenant=mimsy
type: kubernetes.io/dockerconfigjson
data:
    .dockerconfigjson: ENC[AES256_GCM,data:8zEh8fYjoWewwT3yis5YYUIrBQusgbU+4ZjHcc4g2/fT+S3QxsqGZHHTP5lzDKOKTx38KdLZmRZ/Pu+wW0bTF7v4DwfL67JPtNHC7XBSc4l2f2ynYMYvZnp0cfUtX73vR3X9qwF7MmKou14f36XlKeOkKCR0H6dEprajn0UX5l1d7I2NrFsUsIWBVLLnq9UodEH28DkAEpzCMH20O6qkr+t5yS5dCKGkRK27NqvHr+1/F2P1LGF1F0Imb1qlefzpLziNd2izjsvHr+r9eLulMbfxUZgH48CimrclUZBG2JdC/69sFpdnP04azW86eow3mPIVRx9+trqIHzq6MhFPAwa7OdYQ+Q3VdQViit+lWpRsA1tZbSwHtcFMkNxvpt5X,iv:068l/kkcsb0fsRP//GWSySzZJOoaqltHap4m4Dyxu2s=,tag:sGhuPJ8Fxx8LOoToejUAzA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ch3x67ckp8tsw87xfn4m4kn237jnw2yqsvvv46tvapkrx3nyq9ksvjt6eq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1ZThwRlA5SFZ4Ykt6dlVk
            UnN1YXpydmc4MGF1RWttQWdVQ2xtSzNvYVhRClYxa0tMQmJ2ZWo4TVlrU25VZksr
            ejI0dmd4Z05CWGhYR2VoNVpEMXNOUUEKLS0tIDVzcHRFM0RQU29pSTZLOEVFaytU
            Ri9UTjdDVTV0T1dCTmU1UVpYRnFud0kKz3qT41pD1UwWIGBWSjld7iXP+/73ETgk
            aHTNtxi5RVLsrFF10FsEJZC0wYRML/Rxh4w8f1IoXtTswUH4hEX1aQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-14T16:01:06Z"
    mac: ENC[AES256_GCM,data:aLZQEBbOxI8z7JU+cdXJyUPxt1i5ByDG6ev4NdK7tALmfceefefNC6HJuVvL9WKTIX306ESmuSxWhbVoE3E9ZO+GCFFOMVBg3NUgPjdYJZ5mIDBx9wUYBb5pbdBcfzcdVa+Y/W2WJtCtOZ64ER6MrUhxve/z43X089njq8lXDmw=,iv:PZpJgk2vnxUz2ksul9xoaLPATB7+NN60unIRx7EOJRY=,tag:t2atxwRT3Pw08Z2wozSvSQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
