apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  namespace: mimsy
  labels:
    app: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      namespace: mimsy
      labels:
        app: web
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: web
          image: ghcr.io/mimsy-cms/web:20250819-193954-2d67f34 # {"$imagepolicy": "mimsy:web"}
          env:
            - name: PUBLIC_API_URL
              value: "https://cms.mimsy.kodai.ch/api"
          ports:
            - name: http
              containerPort: 3000
          resources:
            requests:
              cpu: 250m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
  strategy:
    type: RollingUpdate
