name: Bug Report
description: File a bug report to help us improve
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

  - type: checkboxes
    id: version
    attributes:
      label: Version
      description: Please confirm which version you're using
      options:
        - label: I'm using the latest changes (dev environment)
        - label: I'm using the cloud version
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Minimal Reproduction Example
      description: |
        Please provide a minimal reproduction example. You can either:
        - Provide a link to a reproduction repository
        - Include code blocks with the minimal code needed to reproduce the issue
      placeholder: |
        Either paste a link here or provide code blocks:

        ```javascript
        // Your minimal reproduction code here
        ```
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: Describe what you expected to happen...
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: Describe what actually happened...
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the problem here (screenshots, error messages, etc.)
      placeholder: Any additional information that might help...
