apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: landing
  namespace: mimsy
spec:
  interval: 1m
  sourceRef:
    kind: GitRepository
    name: mimsy
  decryption:
    provider: sops
    secretRef:
      name: age-secret
  path: ./flux/apps/landing/
  prune: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cms
  namespace: mimsy
spec:
  interval: 1m
  sourceRef:
    kind: GitRepository
    name: mimsy
  decryption:
    provider: sops
    secretRef:
      name: age-secret
  path: ./flux/apps/cms/
  prune: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: slides-demo
  namespace: mimsy
spec:
  interval: 1m
  sourceRef:
    kind: GitRepository
    name: mimsy
  decryption:
    provider: sops
    secretRef:
      name: age-secret
  path: ./flux/apps/slides-demo/
  prune: true
