apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: landing
  namespace: mimsy
spec:
  interval: 1m
  kubeConfig:
    secretRef:
      name: gitops-reconciler-kubeconfig
      key: kubeconfig
  sourceRef:
    kind: GitRepository
    name: mimsy
  decryption:
    provider: sops
    secretRef:
      name: age-secret
  path: ./flux/apps/landing/
  prune: true
