// Code generated by MockGen. DO NOT EDIT.
// Source: internal/sync/repository.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"
	time "time"

	gomock "github.com/golang/mock/gomock"
	sync "github.com/mimsy-cms/mimsy/internal/sync"
	mimsy_schema "github.com/mimsy-cms/mimsy/pkg/mimsy_schema"
)

// MockSyncStatusRepository is a mock of SyncStatusRepository interface.
type MockSyncStatusRepository struct {
	ctrl     *gomock.Controller
	recorder *MockSyncStatusRepositoryMockRecorder
}

// MockSyncStatusRepositoryMockRecorder is the mock recorder for MockSyncStatusRepository.
type MockSyncStatusRepositoryMockRecorder struct {
	mock *MockSyncStatusRepository
}

// NewMockSyncStatusRepository creates a new mock instance.
func NewMockSyncStatusRepository(ctrl *gomock.Controller) *MockSyncStatusRepository {
	mock := &MockSyncStatusRepository{ctrl: ctrl}
	mock.recorder = &MockSyncStatusRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSyncStatusRepository) EXPECT() *MockSyncStatusRepositoryMockRecorder {
	return m.recorder
}

// CreateIfNotExists mocks base method.
func (m *MockSyncStatusRepository) CreateIfNotExists(repo, commitSha, commitMessage string, commitDate time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateIfNotExists", repo, commitSha, commitMessage, commitDate)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateIfNotExists indicates an expected call of CreateIfNotExists.
func (mr *MockSyncStatusRepositoryMockRecorder) CreateIfNotExists(repo, commitSha, commitMessage, commitDate interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateIfNotExists", reflect.TypeOf((*MockSyncStatusRepository)(nil).CreateIfNotExists), repo, commitSha, commitMessage, commitDate)
}

// GetActiveMigration mocks base method.
func (m *MockSyncStatusRepository) GetActiveMigration(repo string) (*sync.SyncStatus, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetActiveMigration", repo)
	ret0, _ := ret[0].(*sync.SyncStatus)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetActiveMigration indicates an expected call of GetActiveMigration.
func (mr *MockSyncStatusRepositoryMockRecorder) GetActiveMigration(repo interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetActiveMigration", reflect.TypeOf((*MockSyncStatusRepository)(nil).GetActiveMigration), repo)
}

// GetLastSyncedCommit mocks base method.
func (m *MockSyncStatusRepository) GetLastSyncedCommit(repo string) (*sync.SyncStatus, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLastSyncedCommit", repo)
	ret0, _ := ret[0].(*sync.SyncStatus)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLastSyncedCommit indicates an expected call of GetLastSyncedCommit.
func (mr *MockSyncStatusRepositoryMockRecorder) GetLastSyncedCommit(repo interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLastSyncedCommit", reflect.TypeOf((*MockSyncStatusRepository)(nil).GetLastSyncedCommit), repo)
}

// GetRecentStatuses mocks base method.
func (m *MockSyncStatusRepository) GetRecentStatuses(limit int) ([]sync.SyncStatus, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRecentStatuses", limit)
	ret0, _ := ret[0].([]sync.SyncStatus)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRecentStatuses indicates an expected call of GetRecentStatuses.
func (mr *MockSyncStatusRepositoryMockRecorder) GetRecentStatuses(limit interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRecentStatuses", reflect.TypeOf((*MockSyncStatusRepository)(nil).GetRecentStatuses), limit)
}

// GetStatus mocks base method.
func (m *MockSyncStatusRepository) GetStatus(repo string) (*sync.SyncStatus, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStatus", repo)
	ret0, _ := ret[0].(*sync.SyncStatus)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStatus indicates an expected call of GetStatus.
func (mr *MockSyncStatusRepositoryMockRecorder) GetStatus(repo interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStatus", reflect.TypeOf((*MockSyncStatusRepository)(nil).GetStatus), repo)
}

// MarkAsActive mocks base method.
func (m *MockSyncStatusRepository) MarkAsActive(repo, commitSha string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkAsActive", repo, commitSha)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkAsActive indicates an expected call of MarkAsActive.
func (mr *MockSyncStatusRepositoryMockRecorder) MarkAsActive(repo, commitSha interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkAsActive", reflect.TypeOf((*MockSyncStatusRepository)(nil).MarkAsActive), repo, commitSha)
}

// MarkAsSkipped mocks base method.
func (m *MockSyncStatusRepository) MarkAsSkipped(repo, commitSha string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkAsSkipped", repo, commitSha)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkAsSkipped indicates an expected call of MarkAsSkipped.
func (mr *MockSyncStatusRepositoryMockRecorder) MarkAsSkipped(repo, commitSha interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkAsSkipped", reflect.TypeOf((*MockSyncStatusRepository)(nil).MarkAsSkipped), repo, commitSha)
}

// MarkError mocks base method.
func (m *MockSyncStatusRepository) MarkError(repo, commitSha string, err error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkError", repo, commitSha, err)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkError indicates an expected call of MarkError.
func (mr *MockSyncStatusRepositoryMockRecorder) MarkError(repo, commitSha, err interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkError", reflect.TypeOf((*MockSyncStatusRepository)(nil).MarkError), repo, commitSha, err)
}

// SetAppliedMigration mocks base method.
func (m *MockSyncStatusRepository) SetAppliedMigration(repo, commitSha string, migration []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetAppliedMigration", repo, commitSha, migration)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetAppliedMigration indicates an expected call of SetAppliedMigration.
func (mr *MockSyncStatusRepositoryMockRecorder) SetAppliedMigration(repo, commitSha, migration interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetAppliedMigration", reflect.TypeOf((*MockSyncStatusRepository)(nil).SetAppliedMigration), repo, commitSha, migration)
}

// SetManifest mocks base method.
func (m *MockSyncStatusRepository) SetManifest(repo, commitSha string, manifest mimsy_schema.Schema) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetManifest", repo, commitSha, manifest)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetManifest indicates an expected call of SetManifest.
func (mr *MockSyncStatusRepositoryMockRecorder) SetManifest(repo, commitSha, manifest interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetManifest", reflect.TypeOf((*MockSyncStatusRepository)(nil).SetManifest), repo, commitSha, manifest)
}
