apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: mimsy
  labels:
    app: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      namespace: mimsy
      labels:
        app: api
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: api
          image: ghcr.io/mimsy-cms/api:20250819-155153-dec4711 # {"$imagepolicy": "mimsy:api"}
          envFrom:
            - secretRef:
                name: api-secrets
          env:
            - name: POSTGRES_HOST
              value: postgres-cluster-rw.postgres.svc
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_DATABASE
              value: mimsy
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: mimsy
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mimsy
                  key: password
            - name: STORAGE
              value: swift
            - name: GH_REPO
              value: mimsy-cms/mimsy
            - name: GH_APP_ID
              value: "1737622"
          ports:
            - name: http
              containerPort: 3000
          resources:
            requests:
              cpu: 250m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
  strategy:
    type: RollingUpdate
