apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageUpdateAutomation
metadata:
  name: cms
  namespace: mimsy
spec:
  interval: 1m
  sourceRef:
    kind: GitRepository
    name: mimsy
  git:
    checkout:
      ref:
        branch: main
    commit:
      author:
        email: flux-automation+mimsy@kodai.ch
        name: Flux Image Automation
      messageTemplate: |
        Update cms image

        {{range .Updated.Images}}
        - {{.}}
        {{end}}
    push:
      branch: main
  update:
    path: "./flux"
    strategy: Setters
