apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: slides-demo
  namespace: mimsy
spec:
  imageRepositoryRef:
    name: slides-demo
  policy:
    numerical:
      order: asc
  filterTags:
    pattern: "^(?P<date>[0-9]+)-(?P<time>[0-9]+)-([a-zA-Z0-9]*)"
    extract: "$date$time"