alias t := test
alias b := build
alias r := run
alias d := dev

build:
    go build -o bin/mimsy ./main.go

test:
    go test -v ./...

test-coverage:
    go test -v -race -coverprofile=coverage.out ./... 
    go tool cover -html=coverage.out -o coverage.html

run:
    go run ./main.go

dev:
    air