name: Build

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write

jobs:
  changes:
    name: Detect changes
    runs-on: ubuntu-latest
    outputs:
      landing: ${{ steps.changes.outputs.landing }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Detect changes
        uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            landing:
              - 'landing/**'

  build-landing:
    runs-on: ubuntu-latest
    needs: changes
    if: needs.changes.outputs.landing == 'true'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build and push docker
        uses: docker/build-push-action@v4
        with:
          context: landing
          push: true
          tags: ghcr.io/mimsy-cms/landing:latest
          cache-from: type=registry,ref=ghcr.io/mimsy-cms/landing:cache
          cache-to: type=registry,ref=ghcr.io/mimsy-cms/landing:cache,mode=max
