name: Build

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write

jobs:
  changes:
    name: Detect changes
    runs-on: ubuntu-latest
    outputs:
      landing: ${{ steps.changes.outputs.landing }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Detect changes
        uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            landing:
              - 'landing/**'

  build-landing:
    runs-on: ubuntu-latest
    needs: changes
    if: needs.changes.outputs.landing == 'true'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Buildx
        uses: docker/setup-buildx-action@v3

      - name: Generate metadata
        uses: docker/metadata-action@v5
        id: metadata
        with:
          images: ghcr.io/mimsy-cms/landing
          tags: latest

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push docker
        uses: docker/build-push-action@v6
        with:
          context: landing
          push: true
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}
          cache-from: type=gha,scope=ghcr.io/mimsy-cms/landing
          cache-to: type=gha,scope=ghcr.io/mimsy-cms/landing,mode=max
